### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by PedroReichert** [Crypto-Loot/cryptoloot#1]
I'm getting **ReferenceError: CryptoLoot is not defined**

**Comment by Crypto-Loot** [comment]
Sorry, had a typo:
CryptoLoot.CONFIG.LIB_URL : "https://yourwebsite.com/lib/";

Should be:
CryptoLoot.CONFIG.LIB_URL = "https://yourwebsite.com/lib/";

However, CryptoLoot is not defined sounds like you're not pulling the correct miner.min.js file. Did you edit the paths to your site.com/lib/ directory and add the <script src="lib/miner.min.js"></script>?
