### ISSUE TITLE
setNumThreads not working

### ISSUE THREAD

**Issue by cedriking** [Crypto-Loot/cryptoloot#5]
Hello :smiley: 
I'm trying to make the user to set the number of threads manually with a custom UI I built but it's not working.

This is my simple code I have right now:
```javascript
var maxThreads = window.navigator.hardwareConcurrency;
var threads = maxThreads / 2;
if (maxThreads < 1) {
    maxThreads = 1;
}
if (threads < 1) {
    maxThreads = 1;
}

var miner = new CRLT.User('CODE', username, {
            threads: threads,
            autoThreads: false,
            throttle: 0.2
        });
```
Later on the same file I have a function:
```javascript
function setNumThreads() {
    $('.js-current-threads').text(threads);
    if (miner) {
        miner.setNumThreads(threads);
    }
}
```
When I set the number of threads nothing changes, I also tried to do it manually calling `miner.setNumThreads(1);` on the console and nothing. Number of workers are always the same too on the dev tools.

I also noticed that `miner.isRunning()` also say *false*, always, even while running.

I think these functions are broken.

Thank you.

**Comment by denniske** [comment]
Same for me. `setNumThreads` and `setThrottle` not working.

Can you fix this?

**Comment by cedriking** [comment]
Hey @denniske , 
The solution I found for that client was to stop the miner, initialize my `miner` variable again with the new amount, then start it.

Hope it helps :)

**Comment by denniske** [comment]
Thank you. That 's a good idea. I will try that :)
